sudo: required

notifications:
  email:
    recipients:
      - contato@gabrielferreira.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
language: python

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python manage.py migrate"
# command to run tests
script: coverage run manage.py test && coverage xml && python-codacy-coverage -r coverage.xml
branches:
  only:
    - master
after_success: coveralls
